
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sns
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123123


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace