INSERT INTO USER (ID, EMAIL, PW, NICKNAME,GENDER,CREATE_DATE) values(1, 'test','test','test', 0, NOW());
INSERT INTO USER (ID, EMAIL, PW, NICKNAME,GENDER,CREATE_DATE) values(2, 'test2','test2','test2', 1, NOW());

INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) VALUE (1, 'ADMIN');
INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) VALUE (2, 'USER');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (2, 1);