INSERT INTO USER (ID, EMAIL, PW, NICKNAME,GENDER,CREATE_DATE) values(1, 'test','$2a$10$KSXevhDsJWyIH2NlYD/N1ud5cOEZZIPKshAzkEu1JB4RtmcMszzZW','test', 0, NOW());
INSERT INTO USER (ID, EMAIL, PW, NICKNAME,GENDER,CREATE_DATE) values(2, 'test2','$2a$10$Gb3saK1UgfrAI5oUIjzX9u/ePZMXyOLwCPv94ZVzmCoKGImANYc0i','test2', 1, NOW());

INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) VALUE (1, 'ADMIN');
INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) VALUE (2, 'USER');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (2, 1);